select 
	DBED.DTEDG199.IMG_KIND, 
	DBED.DTEDG199.IMG_NAME, 
	DBED.DTEDG199.MNG_DIV_NO,  
	DBED.DTEDG199.PERSIST_YEAR,
	DBED.DTEDG199.PERSIST_MONTH,
	DBED.DTEDG199.PERSIST_DAY,
	DBED.DTEDG199.UPDT_DATE as CHG_DATE,
	'COMP' as CHG_ID,
	'COMP' as CHG_NAME,
	'COMP' as CHG_DIV_NO,
	'DTEDG199' AS SRC_TABLE,
	DBED.DTEDG199.IS_ENT_DIV,
	DBED.DTEDG199.IS_ENT_WRS,
	DBED.DTEDG199.CARGO_ENT_WRS,
    VALUE(DBAV.DTAVG992.DOCNO,'') AS BCH_SCAN
from DBED.DTEDG199 LEFT JOIN DBAV.DTAVG992 ON (DBED.DTEDG199.IMG_KIND = DBAV.DTAVG992.DOCNO)
where 1=1
[ and DBED.DTEDG199.IMG_KIND = ':IMG_KIND' ]
union
select 
	DBED.DTEDB992.IMG_KIND, 
	DBED.DTEDB992.IMG_NAME, 
	DBED.DTEDB992.MNG_DIV_NO, 
	DBED.DTEDB992.PERSIST_YEAR,
	DBED.DTEDB992.PERSIST_MONTH,
	DBED.DTEDB992.PERSIST_DAY,
	date(DBED.DTEDB992.CHG_DATE) as CHG_DATE,
	DBED.DTEDB992.CHG_ID,
	DBED.DTEDB992.CHG_NAME,
	DBED.DTEDB992.CHG_DIV_NO,
	'DTEDB992' AS SRC_TABLE,
	DBED.DTEDB992.IS_ENT_DIV,
	DBED.DTEDB992.IS_ENT_WRS,
	DBED.DTEDB992.CARGO_ENT_WRS,
    '' AS BCH_SCAN
from DBED.DTEDB992
where 1=1
[ and DBED.DTEDB992.IMG_KIND = ':IMG_KIND' ]
with ur
